[package]
name = "wasmlib"
version = "0.1.0"
authors = ["Alexandra Østermark <alex.cramt@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
regex = "1.3.5"
console_error_panic_hook = "0.1.6"

[lib]
crate-type = ["cdylib"]
